2025-01-24 09:44:08,218 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 09:47:11,614 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 09:50:31,627 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 09:50:34,208 (WARNING)- django.request- Not Found: /
2025-01-24 10:50:27,316 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 10:50:44,781 (INFO)- django.utils.autoreload- /Users/andrey_zaharov/code/drf_react_template/back/back/settings.py changed, reloading.
2025-01-24 10:50:45,079 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 10:50:46,025 (WARNING)- django.request- Not Found: /api/current_user/
2025-01-24 10:50:47,294 (WARNING)- django.request- Not Found: /api/current_user/
2025-01-24 10:50:48,554 (WARNING)- django.request- Not Found: /api/current_user/
2025-01-24 10:51:00,193 (WARNING)- django.request- Not Found: /api/current_user/
2025-01-24 10:51:00,503 (INFO)- django.utils.autoreload- /Users/andrey_zaharov/code/drf_react_template/back/api/urls.py changed, reloading.
2025-01-24 10:51:00,780 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 10:51:00,971 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:51:09,184 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:51:10,625 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:51:11,344 (WARNING)- django.request- Not Found: /
2025-01-24 10:51:53,186 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 10:52:22,661 (ERROR)- django.request- Internal Server Error: /admin/api/customuser/1/change/
Traceback (most recent call last):
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 303, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1819, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/transaction.py", line 263, in __exit__
    connection.commit()
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 327, in commit
    self._commit()
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 302, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 303, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
2025-01-24 10:53:06,507 (ERROR)- django.request- Internal Server Error: /admin/api/customuser/1/change/
Traceback (most recent call last):
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 303, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1819, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/transaction.py", line 263, in __exit__
    connection.commit()
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 327, in commit
    self._commit()
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 302, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/andrey_zaharov/code/drf_react_template/back/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 303, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
2025-01-24 10:55:14,459 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 10:55:24,418 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 10:55:44,001 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:55:46,723 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:55:47,248 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:55:48,791 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:55:52,789 (WARNING)- django.request- Unauthorized: /api/login/
2025-01-24 10:55:59,365 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 10:56:01,512 (WARNING)- django.request- Not Found: /
2025-01-24 10:56:04,696 (WARNING)- django.request- Not Found: /
2025-01-24 10:56:58,561 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 11:01:53,441 (WARNING)- django.request- Method Not Allowed: /api/logout/
2025-01-24 11:02:02,723 (WARNING)- django.request- Method Not Allowed: /api/logout/
2025-01-24 11:02:39,937 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:02:39,941 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:08:03,163 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:08:05,381 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:08:18,987 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:08:35,044 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:09:29,073 (INFO)- django.utils.autoreload- /Users/andrey_zaharov/code/drf_react_template/back/api/views.py changed, reloading.
2025-01-24 11:09:29,405 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 11:09:31,538 (INFO)- django.utils.autoreload- /Users/andrey_zaharov/code/drf_react_template/back/api/views.py changed, reloading.
2025-01-24 11:09:31,730 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 11:09:32,840 (INFO)- django.utils.autoreload- /Users/andrey_zaharov/code/drf_react_template/back/api/views.py changed, reloading.
2025-01-24 11:09:33,025 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
2025-01-24 11:09:34,383 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:09:40,309 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:09:43,139 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:09:46,515 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:09:48,452 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:09:49,604 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:10:27,445 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:10:29,122 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:10:39,441 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:10:39,447 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:10:43,168 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:10:43,172 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:11:54,831 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:11:56,401 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:12:03,860 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:12:03,866 (WARNING)- django.request- Forbidden: /api/logout/
2025-01-24 11:14:26,955 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:14:38,131 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:15:11,423 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:15:11,470 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:15:11,791 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:15:12,822 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:15:25,395 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:16:04,948 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:16:16,187 (WARNING)- django.request- Forbidden: /api/current_user/
2025-01-24 11:17:00,026 (WARNING)- django.request- Forbidden: /api/current_user/
